import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Lang = "en" | "ar";

const dict = {
  brand: { en: "Almwanaa Company", ar: "شركة الموانئ" },
  brandShort: { en: "Almwanaa", ar: "الموانئ" },
  tagline: { en: "Track every shipment, anywhere.", ar: "تتبّع كل شحنة، في أي مكان." },
  heroTitle: { en: "Shipping made simple.", ar: "الشحن بأبسط صورة." },
  heroSub: { en: "Track shipments, manage deliveries, and stay informed.", ar: "تتبع الشحنات وإدارة التسليم والبقاء على اطلاع." },
  trackCta: { en: "Track a shipment", ar: "تتبع شحنة" },
  signIn: { en: "Sign in", ar: "تسجيل الدخول" },
  signUp: { en: "Sign up", ar: "إنشاء حساب" },
  signOut: { en: "Sign out", ar: "تسجيل الخروج" },
  back: { en: "Back", ar: "رجوع" },
  email: { en: "Email", ar: "البريد الإلكتروني" },
  password: { en: "Password", ar: "كلمة المرور" },
  newPassword: { en: "New password", ar: "كلمة المرور الجديدة" },
  username: { en: "Username", ar: "اسم المستخدم" },
  fullName: { en: "Full name", ar: "الاسم الكامل" },
  phone: { en: "Phone number", ar: "رقم الهاتف" },
  governorate: { en: "Governorate", ar: "المحافظة" },
  area: { en: "Area / District", ar: "المنطقة / الحي" },
  haveAccount: { en: "Already have an account?", ar: "لديك حساب؟" },
  noAccount: { en: "Don't have an account?", ar: "ليس لديك حساب؟" },
  // tracking
  trackTitle: { en: "Track your shipment", ar: "تتبع شحنتك" },
  trackPlaceholder: { en: "Enter tracking number", ar: "أدخل رقم التتبع" },
  trackBtn: { en: "Track", ar: "تتبع" },
  notFound: { en: "Shipment not found.", ar: "لم يتم العثور على الشحنة." },
  // shipment fields
  trackingNo: { en: "Tracking #", ar: "رقم التتبع" },
  customer: { en: "Customer", ar: "العميل" },
  origin: { en: "Origin", ar: "المصدر" },
  destination: { en: "Destination", ar: "الوجهة" },
  shipmentType: { en: "Type", ar: "النوع" },
  weight: { en: "Weight (kg)", ar: "الوزن (كجم)" },
  status: { en: "Status", ar: "الحالة" },
  eta: { en: "Expected arrival", ar: "تاريخ الوصول المتوقع" },
  remaining: { en: "Remaining", ar: "المتبقي" },
  notes: { en: "Internal notes", ar: "ملاحظات داخلية" },
  customerNotes: { en: "Customer notes", ar: "ملاحظات للعميل" },
  estimatedCost: { en: "Estimated cost", ar: "الكلفة التقديرية" },
  cbm: { en: "Volume", ar: "الحجم" },
  description: { en: "Shipment description", ar: "وصف الشحنة" },
  descriptionPlaceholder: { en: "Clothes, Electronics, etc.", ar: "ملابس، إلكترونيات، إلخ" },
  timeline: { en: "Timeline", ar: "السجل الزمني" },
  created: { en: "Created", ar: "تاريخ الإنشاء" },
  updated: { en: "Last updated", ar: "آخر تحديث" },
  selectCustomer: { en: "Select customer", ar: "اختر العميل" },
  autoGenerated: { en: "Auto-generated", ar: "يُنشأ تلقائياً" },
  // status enum
  s_received: { en: "Received", ar: "تم الاستلام" },
  s_in_warehouse: { en: "In Warehouse", ar: "في المستودع" },
  s_ready: { en: "Ready for Shipping", ar: "جاهزة للشحن" },
  s_shipped: { en: "Shipped", ar: "تم الشحن" },
  s_in_transit: { en: "In Transit", ar: "في الطريق" },
  s_arrived_destination: { en: "Arrived at Destination", ar: "وصلت بلد الوجهة" },
  s_out_for_delivery: { en: "Out for Delivery", ar: "في طريقها للتسليم" },
  s_delivered: { en: "Delivered", ar: "تم التسليم" },
  s_delayed: { en: "Delayed", ar: "متأخرة" },
  s_cancelled: { en: "Cancelled", ar: "ملغية" },
  s_received_warehouse: { en: "Received at Warehouse", ar: "تم الاستلام في المستودع" },
  s_in_sea_transit: { en: "In Sea Transit", ar: "في النقل البحري" },
  s_arrived_umm_qasr: { en: "Arrived at Umm Qasr Port", ar: "وصلت ميناء أم قصر" },
  s_arrived_baghdad: { en: "Arrived at Baghdad Warehouse", ar: "وصلت مستودع بغداد" },
  // actions
  add: { en: "Add", ar: "إضافة" },
  save: { en: "Save", ar: "حفظ" },
  edit: { en: "Edit", ar: "تعديل" },
  delete: { en: "Delete", ar: "حذف" },
  cancel: { en: "Cancel", ar: "إلغاء" },
  search: { en: "Search...", ar: "بحث..." },
  filter: { en: "Filter", ar: "تصفية" },
  all: { en: "All", ar: "الكل" },
  send: { en: "Send", ar: "إرسال" },
  confirm: { en: "Confirm", ar: "تأكيد" },
  open: { en: "Open", ar: "فتح" },
  // dashboard
  dashboardTitle: { en: "Dashboard", ar: "لوحة التحكم" },
  adminDashboard: { en: "Admin Dashboard", ar: "لوحة المسؤول" },
  totalShipments: { en: "Total", ar: "الإجمالي" },
  totalCustomers: { en: "Customers", ar: "العملاء" },
  activeShipments: { en: "Active", ar: "نشطة" },
  deliveredShipments: { en: "Delivered", ar: "تم التسليم" },
  delayedShipments: { en: "Delayed", ar: "متأخرة" },
  monthlyStats: { en: "Last 6 months", ar: "آخر 6 أشهر" },
  recent: { en: "Recent shipments", ar: "أحدث الشحنات" },
  myShipments: { en: "My shipments", ar: "شحناتي" },
  addShipment: { en: "Add Shipment", ar: "إضافة شحنة" },
  manageShipments: { en: "Shipment Management", ar: "إدارة الشحنات" },
  allShipments: { en: "All Shipments", ar: "كل الشحنات" },
  sendNotification: { en: "Send Notification", ar: "إرسال إشعار" },
  toAll: { en: "Send to all users", ar: "إرسال للجميع" },
  toSpecific: { en: "Send to specific customer", ar: "إرسال لعميل محدد" },
  title: { en: "Title", ar: "العنوان" },
  message: { en: "Message", ar: "الرسالة" },
  noCustomerSelected: { en: "Select a customer to view their shipments.", ar: "اختر عميلاً لعرض شحناته." },
  adminsOnly: { en: "Only administrators can use this feature.", ar: "هذه الميزة متاحة للمسؤولين فقط." },
  noPermission: { en: "You don't have permission to perform this action.", ar: "ليس لديك صلاحية للقيام بهذا الإجراء." },
  // address book
  addressBook: { en: "Address Book", ar: "دفتر العناوين" },
  name: { en: "Name", ar: "الاسم" },
  country: { en: "Country", ar: "الدولة" },
  city: { en: "City", ar: "المدينة" },
  address: { en: "Address", ar: "العنوان" },
  // announcements / news
  news: { en: "Latest News", ar: "آخر الأخبار" },
  newsManagement: { en: "News Management", ar: "إدارة الأخبار" },
  newAnnouncement: { en: "New announcement", ar: "إعلان جديد" },
  title_en: { en: "Title (English)", ar: "العنوان (إنجليزي)" },
  title_ar: { en: "Title (Arabic)", ar: "العنوان (عربي)" },
  body_en: { en: "Body (English)", ar: "المحتوى (إنجليزي)" },
  body_ar: { en: "Body (Arabic)", ar: "المحتوى (عربي)" },
  published: { en: "Published", ar: "منشور" },
  // notifications
  notifications: { en: "Notifications", ar: "التنبيهات" },
  markAllRead: { en: "Mark all read", ar: "تعليم الكل كمقروء" },
  noNotifications: { en: "No notifications yet.", ar: "لا توجد تنبيهات بعد." },
  shipmentUpdateTitle: { en: "Shipment update", ar: "تحديث الشحنة" },
  shipmentStatusUpdatedTo: { en: "Shipment status updated to", ar: "تم تحديث حالة الشحنة إلى" },
  copyTracking: { en: "Copy tracking number", ar: "نسخ رقم التتبع" },
  trackingCopied: { en: "Tracking number copied", ar: "تم نسخ رقم التتبع" },
  // accounts
  accounts: { en: "Accounts Management", ar: "إدارة الحسابات" },
  registeredMembers: { en: "Registered Members", ar: "الأعضاء المسجلون" },
  staff: { en: "Staff", ar: "الموظفون" },
  customers: { en: "Customers", ar: "العملاء" },
  addEmployee: { en: "Add Employee", ar: "إضافة موظف" },
  newStaff: { en: "Add Staff Account", ar: "إضافة حساب موظف" },
  accountDetails: { en: "Account Details", ar: "تفاصيل الحساب" },
  resetPassword: { en: "Reset Password", ar: "إعادة تعيين كلمة المرور" },
  deleteAccount: { en: "Delete Account", ar: "حذف الحساب" },
  confirmDelete: { en: "Are you sure? This permanently removes the account and all related data.", ar: "هل أنت متأكد؟ سيتم حذف الحساب وجميع البيانات المرتبطة نهائياً." },
  // offices
  offices: { en: "Our Offices", ar: "مكاتبنا" },
  officesManagement: { en: "Offices Management", ar: "إدارة المكاتب" },
  addOffice: { en: "Add Office", ar: "إضافة مكتب" },
  viewOnly: { en: "View only", ar: "عرض فقط" },
  // shipment actions
  deleteShipment: { en: "Delete Shipment", ar: "حذف الشحنة" },
  shipmentDetails: { en: "Shipment Details", ar: "تفاصيل الشحنة" },
  // misc
  loading: { en: "Loading...", ar: "جارٍ التحميل..." },
  empty: { en: "Nothing to show yet.", ar: "لا يوجد شيء حاليًا." },
  welcome: { en: "Welcome", ar: "مرحبًا" },
  role: { en: "Role", ar: "الدور" },
  admin: { en: "Server Admin", ar: "إدارة السيرفر" },
  manager: { en: "Company Manager", ar: "مدير الشركة" },
  employee: { en: "Employee", ar: "موظف" },
  deleteOffice: { en: "Delete Office", ar: "حذف المكتب" },
  deleteNews: { en: "Delete News", ar: "حذف الخبر" },
  confirmDeleteItem: { en: "Are you sure? This item will be permanently removed from the system.", ar: "هل أنت متأكد؟ سيتم حذف هذا العنصر نهائياً من النظام." },
  
  sent: { en: "Sent", ar: "تم الإرسال" },
  // settings
  settings: { en: "Settings", ar: "الإعدادات" },
  accountSettings: { en: "Account Settings", ar: "إعدادات الحساب" },
  changePassword: { en: "Change Password", ar: "تغيير كلمة المرور" },
  updatePassword: { en: "Update Password", ar: "تحديث كلمة المرور" },
  passwordUpdated: { en: "Password updated successfully", ar: "تم تحديث كلمة المرور بنجاح" },
  saved: { en: "Saved", ar: "تم الحفظ" },
  footer: { en: "© 2026 Almwanaa Company. All rights reserved.", ar: "© 2026 شركة الموانئ. جميع الحقوق محفوظة." },
} as const;

type DictKey = keyof typeof dict;

type Ctx = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (k: DictKey) => string;
  dir: "ltr" | "rtl";
};
const I18nCtx = createContext<Ctx | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("ar");

  useEffect(() => {
    const saved = (typeof window !== "undefined" && (localStorage.getItem("lang") as Lang)) || "ar";
    setLangState(saved);
  }, []);

  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = lang;
      document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    }
  }, [lang]);

  const setLang = (l: Lang) => {
    setLangState(l);
    if (typeof window !== "undefined") localStorage.setItem("lang", l);
  };

  const t = (k: DictKey) => dict[k]?.[lang] ?? String(k);
  return (
    <I18nCtx.Provider value={{ lang, setLang, t, dir: lang === "ar" ? "rtl" : "ltr" }}>
      {children}
    </I18nCtx.Provider>
  );
}

export function useI18n() {
  const ctx = useContext(I18nCtx);
  if (!ctx) throw new Error("useI18n must be used inside I18nProvider");
  return ctx;
}
