/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as OfficesRouteImport } from './routes/offices'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOfficesManageRouteImport } from './routes/_authenticated/offices-manage'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNewsManageRouteImport } from './routes/_authenticated/news-manage'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminShipmentsRouteImport } from './routes/_authenticated/admin-shipments'
import { Route as AuthenticatedAdminNotifyRouteImport } from './routes/_authenticated/admin-notify'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin-customers'
import { Route as AuthenticatedAdminAddRouteImport } from './routes/_authenticated/admin-add'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAddressesRouteImport } from './routes/_authenticated/addresses'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedShipmentsIndexRouteImport } from './routes/_authenticated/shipments.index'
import { Route as AuthenticatedShipmentsIdRouteImport } from './routes/_authenticated/shipments.$id'
import { Route as AuthenticatedAccountsIdRouteImport } from './routes/_authenticated/accounts.$id'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesRoute = OfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfficesManageRoute =
  AuthenticatedOfficesManageRouteImport.update({
    id: '/offices-manage',
    path: '/offices-manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewsManageRoute = AuthenticatedNewsManageRouteImport.update({
  id: '/news-manage',
  path: '/news-manage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminShipmentsRoute =
  AuthenticatedAdminShipmentsRouteImport.update({
    id: '/admin-shipments',
    path: '/admin-shipments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotifyRoute =
  AuthenticatedAdminNotifyRouteImport.update({
    id: '/admin-notify',
    path: '/admin-notify',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/admin-customers',
    path: '/admin-customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAddRoute = AuthenticatedAdminAddRouteImport.update({
  id: '/admin-add',
  path: '/admin-add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddressesRoute = AuthenticatedAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShipmentsIndexRoute =
  AuthenticatedShipmentsIndexRouteImport.update({
    id: '/shipments/',
    path: '/shipments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShipmentsIdRoute =
  AuthenticatedShipmentsIdRouteImport.update({
    id: '/shipments/$id',
    path: '/shipments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsIdRoute = AuthenticatedAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/offices': typeof OfficesRoute
  '/track': typeof TrackRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/addresses': typeof AuthenticatedAddressesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-add': typeof AuthenticatedAdminAddRoute
  '/admin-customers': typeof AuthenticatedAdminCustomersRoute
  '/admin-notify': typeof AuthenticatedAdminNotifyRoute
  '/admin-shipments': typeof AuthenticatedAdminShipmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/news-manage': typeof AuthenticatedNewsManageRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/offices-manage': typeof AuthenticatedOfficesManageRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/shipments/': typeof AuthenticatedShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/offices': typeof OfficesRoute
  '/track': typeof TrackRoute
  '/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/addresses': typeof AuthenticatedAddressesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-add': typeof AuthenticatedAdminAddRoute
  '/admin-customers': typeof AuthenticatedAdminCustomersRoute
  '/admin-notify': typeof AuthenticatedAdminNotifyRoute
  '/admin-shipments': typeof AuthenticatedAdminShipmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/news-manage': typeof AuthenticatedNewsManageRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/offices-manage': typeof AuthenticatedOfficesManageRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/shipments': typeof AuthenticatedShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/offices': typeof OfficesRoute
  '/track': typeof TrackRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRouteWithChildren
  '/_authenticated/addresses': typeof AuthenticatedAddressesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-add': typeof AuthenticatedAdminAddRoute
  '/_authenticated/admin-customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin-notify': typeof AuthenticatedAdminNotifyRoute
  '/_authenticated/admin-shipments': typeof AuthenticatedAdminShipmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/news-manage': typeof AuthenticatedNewsManageRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/offices-manage': typeof AuthenticatedOfficesManageRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/accounts/$id': typeof AuthenticatedAccountsIdRoute
  '/_authenticated/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/_authenticated/shipments/': typeof AuthenticatedShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/auth'
    | '/offices'
    | '/track'
    | '/accounts'
    | '/addresses'
    | '/admin'
    | '/admin-add'
    | '/admin-customers'
    | '/admin-notify'
    | '/admin-shipments'
    | '/dashboard'
    | '/news-manage'
    | '/notifications'
    | '/offices-manage'
    | '/settings'
    | '/accounts/$id'
    | '/shipments/$id'
    | '/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/auth'
    | '/offices'
    | '/track'
    | '/accounts'
    | '/addresses'
    | '/admin'
    | '/admin-add'
    | '/admin-customers'
    | '/admin-notify'
    | '/admin-shipments'
    | '/dashboard'
    | '/news-manage'
    | '/notifications'
    | '/offices-manage'
    | '/settings'
    | '/accounts/$id'
    | '/shipments/$id'
    | '/shipments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/announcements'
    | '/auth'
    | '/offices'
    | '/track'
    | '/_authenticated/accounts'
    | '/_authenticated/addresses'
    | '/_authenticated/admin'
    | '/_authenticated/admin-add'
    | '/_authenticated/admin-customers'
    | '/_authenticated/admin-notify'
    | '/_authenticated/admin-shipments'
    | '/_authenticated/dashboard'
    | '/_authenticated/news-manage'
    | '/_authenticated/notifications'
    | '/_authenticated/offices-manage'
    | '/_authenticated/settings'
    | '/_authenticated/accounts/$id'
    | '/_authenticated/shipments/$id'
    | '/_authenticated/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  OfficesRoute: typeof OfficesRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices': {
      id: '/offices'
      path: '/offices'
      fullPath: '/offices'
      preLoaderRoute: typeof OfficesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offices-manage': {
      id: '/_authenticated/offices-manage'
      path: '/offices-manage'
      fullPath: '/offices-manage'
      preLoaderRoute: typeof AuthenticatedOfficesManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news-manage': {
      id: '/_authenticated/news-manage'
      path: '/news-manage'
      fullPath: '/news-manage'
      preLoaderRoute: typeof AuthenticatedNewsManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-shipments': {
      id: '/_authenticated/admin-shipments'
      path: '/admin-shipments'
      fullPath: '/admin-shipments'
      preLoaderRoute: typeof AuthenticatedAdminShipmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-notify': {
      id: '/_authenticated/admin-notify'
      path: '/admin-notify'
      fullPath: '/admin-notify'
      preLoaderRoute: typeof AuthenticatedAdminNotifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-customers': {
      id: '/_authenticated/admin-customers'
      path: '/admin-customers'
      fullPath: '/admin-customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-add': {
      id: '/_authenticated/admin-add'
      path: '/admin-add'
      fullPath: '/admin-add'
      preLoaderRoute: typeof AuthenticatedAdminAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/addresses': {
      id: '/_authenticated/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipments/': {
      id: '/_authenticated/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof AuthenticatedShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipments/$id': {
      id: '/_authenticated/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/shipments/$id'
      preLoaderRoute: typeof AuthenticatedShipmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/$id': {
      id: '/_authenticated/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AuthenticatedAccountsIdRouteImport
      parentRoute: typeof AuthenticatedAccountsRoute
    }
  }
}

interface AuthenticatedAccountsRouteChildren {
  AuthenticatedAccountsIdRoute: typeof AuthenticatedAccountsIdRoute
}

const AuthenticatedAccountsRouteChildren: AuthenticatedAccountsRouteChildren = {
  AuthenticatedAccountsIdRoute: AuthenticatedAccountsIdRoute,
}

const AuthenticatedAccountsRouteWithChildren =
  AuthenticatedAccountsRoute._addFileChildren(
    AuthenticatedAccountsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRouteWithChildren
  AuthenticatedAddressesRoute: typeof AuthenticatedAddressesRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminAddRoute: typeof AuthenticatedAdminAddRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminNotifyRoute: typeof AuthenticatedAdminNotifyRoute
  AuthenticatedAdminShipmentsRoute: typeof AuthenticatedAdminShipmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewsManageRoute: typeof AuthenticatedNewsManageRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOfficesManageRoute: typeof AuthenticatedOfficesManageRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShipmentsIdRoute: typeof AuthenticatedShipmentsIdRoute
  AuthenticatedShipmentsIndexRoute: typeof AuthenticatedShipmentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRouteWithChildren,
  AuthenticatedAddressesRoute: AuthenticatedAddressesRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminAddRoute: AuthenticatedAdminAddRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminNotifyRoute: AuthenticatedAdminNotifyRoute,
  AuthenticatedAdminShipmentsRoute: AuthenticatedAdminShipmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewsManageRoute: AuthenticatedNewsManageRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOfficesManageRoute: AuthenticatedOfficesManageRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShipmentsIdRoute: AuthenticatedShipmentsIdRoute,
  AuthenticatedShipmentsIndexRoute: AuthenticatedShipmentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  OfficesRoute: OfficesRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
